# Form implementation generated from reading ui file 'c:\Users\Zangara\Documents\1-CURSO AX\8460 - TÉCNICAS AVANZADAS DE PROGRAMACIÓN\BBDD\.vscode\LaSegura\CapaVista\VentanaPrincipal.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaPrincipal(object):
    def setupUi(self, VentanaPrincipal):
        VentanaPrincipal.setObjectName("VentanaPrincipal")
        VentanaPrincipal.resize(566, 445)
        self.centralwidget = QtWidgets.QWidget(VentanaPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        VentanaPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VentanaPrincipal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 566, 26))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuCRUD_Autos = QtWidgets.QMenu(self.menubar)
        self.menuCRUD_Autos.setObjectName("menuCRUD_Autos")
        self.menuCRUD_Personas = QtWidgets.QMenu(self.menubar)
        self.menuCRUD_Personas.setObjectName("menuCRUD_Personas")
        self.menuCRUD_Accidentes = QtWidgets.QMenu(self.menubar)
        self.menuCRUD_Accidentes.setObjectName("menuCRUD_Accidentes")
        VentanaPrincipal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaPrincipal)
        self.statusbar.setObjectName("statusbar")
        VentanaPrincipal.setStatusBar(self.statusbar)
        self.actionSalir = QtGui.QAction(VentanaPrincipal)
        self.actionSalir.setObjectName("actionSalir")
        self.actionAutos = QtGui.QAction(VentanaPrincipal)
        self.actionAutos.setObjectName("actionAutos")
        self.actionPersonas = QtGui.QAction(VentanaPrincipal)
        self.actionPersonas.setObjectName("actionPersonas")
        self.actionInformes = QtGui.QAction(VentanaPrincipal)
        self.actionInformes.setObjectName("actionInformes")
        self.actionSiniestros = QtGui.QAction(VentanaPrincipal)
        self.actionSiniestros.setObjectName("actionSiniestros")
        self.actionAccidentes = QtGui.QAction(VentanaPrincipal)
        self.actionAccidentes.setObjectName("actionAccidentes")
        self.menuArchivo.addAction(self.actionSalir)
        self.menuCRUD_Autos.addAction(self.actionAutos)
        self.menuCRUD_Personas.addAction(self.actionPersonas)
        self.menuCRUD_Personas.addSeparator()
        self.menuCRUD_Personas.addAction(self.actionSiniestros)
        self.menuCRUD_Accidentes.addAction(self.actionAccidentes)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuCRUD_Autos.menuAction())
        self.menubar.addAction(self.menuCRUD_Personas.menuAction())
        self.menubar.addAction(self.menuCRUD_Accidentes.menuAction())

        self.retranslateUi(VentanaPrincipal)
        QtCore.QMetaObject.connectSlotsByName(VentanaPrincipal)

    def retranslateUi(self, VentanaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        VentanaPrincipal.setWindowTitle(_translate("VentanaPrincipal", "Sistema de Gestión de Seguros ZANGARITA SRL"))
        self.menuArchivo.setTitle(_translate("VentanaPrincipal", "Archivo"))
        self.menuCRUD_Autos.setTitle(_translate("VentanaPrincipal", "CRUD Autos"))
        self.menuCRUD_Personas.setTitle(_translate("VentanaPrincipal", "CRUD Personas"))
        self.menuCRUD_Accidentes.setTitle(_translate("VentanaPrincipal", "CRUD Accidentes"))
        self.actionSalir.setText(_translate("VentanaPrincipal", "Salir"))
        self.actionSalir.setShortcut(_translate("VentanaPrincipal", "Ctrl+Q"))
        self.actionAutos.setText(_translate("VentanaPrincipal", "Autos"))
        self.actionPersonas.setText(_translate("VentanaPrincipal", "Personas"))
        self.actionInformes.setText(_translate("VentanaPrincipal", "Informes"))
        self.actionSiniestros.setText(_translate("VentanaPrincipal", "Siniestros"))
        self.actionAccidentes.setText(_translate("VentanaPrincipal", "Accidentes"))
